// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7Z37sDFw5ImROQ2aVsJUvqGq01hjxOU',
    appId: '1:649482852438:web:5b1fe342388d4e94ed43f7',
    messagingSenderId: '649482852438',
    projectId: 'hotel-booking-app-projec-1097d',
    authDomain: 'hotel-booking-app-projec-1097d.firebaseapp.com',
    storageBucket: 'hotel-booking-app-projec-1097d.firebasestorage.app',
    measurementId: 'G-7NZS63RF7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd_hKQTQ9M9HU3jdBtkip_mz2BD_u9s6s',
    appId: '1:649482852438:android:77fd670733ce8759ed43f7',
    messagingSenderId: '649482852438',
    projectId: 'hotel-booking-app-projec-1097d',
    storageBucket: 'hotel-booking-app-projec-1097d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSnZfkTwajbBhKn7kQIH2AoVpuSRdmjzk',
    appId: '1:649482852438:ios:43f87455520e02e0ed43f7',
    messagingSenderId: '649482852438',
    projectId: 'hotel-booking-app-projec-1097d',
    storageBucket: 'hotel-booking-app-projec-1097d.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSnZfkTwajbBhKn7kQIH2AoVpuSRdmjzk',
    appId: '1:649482852438:ios:43f87455520e02e0ed43f7',
    messagingSenderId: '649482852438',
    projectId: 'hotel-booking-app-projec-1097d',
    storageBucket: 'hotel-booking-app-projec-1097d.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV7Z37sDFw5ImROQ2aVsJUvqGq01hjxOU',
    appId: '1:649482852438:web:b5ad78a2ebff8e45ed43f7',
    messagingSenderId: '649482852438',
    projectId: 'hotel-booking-app-projec-1097d',
    authDomain: 'hotel-booking-app-projec-1097d.firebaseapp.com',
    storageBucket: 'hotel-booking-app-projec-1097d.firebasestorage.app',
    measurementId: 'G-DXSS19B205',
  );
}
